const BUTTON_LOOP_MIN_SECONDS = 2.5;
const BUTTON_LOOP_MAX_SECONDS = 7;

const TITLE_LOOP_DELAY_SECONDS = 2;
const TITLE_LOOP_MIN_SECONDS = 0;
const TITLE_LOOP_MAX_SECONDS = 0.3;

const ON_CLICK_DELAY_SECONDS = 0.5;

const ANIMATION_MIN_SECONDS = 1;
const ANIMATION_MAX_SECONDS = 2.5;

const DRIP_ANIMATION_RATIO = 0.9;
const DRIP_MIN = 20;
const DRIP_MAX = 100;

const WIGGLE_DISTANCE = 3;
const WIGGLE_MIN_POSITIONS = 11;
const WIGGLE_MAX_POSITIONS = 20;
