const BUTTON_LOOP_MIN_SECONDS = 0;
const BUTTON_LOOP_MAX_SECONDS = 0.5;

const TITLE_LOOP_DELAY_SECONDS = 1.5;
const TITLE_LOOP_MIN_SECONDS = 0;
const TITLE_LOOP_MAX_SECONDS = 0;

const ON_CLICK_DELAY_SECONDS = 0.5;

const ANIMATION_MIN_SECONDS = 0.6;
const ANIMATION_MAX_SECONDS = 2;

const HEADING_ROTATION_ABS_MAX_DEGREES = 360;

const DRIP_ANIMATION_RATIO = 0.9;
const DRIP_MIN = 40;
const DRIP_MAX = 200;

const BREATHE_ANIMATION_RATIO = 0.5;
const BREATHE_ANIMATION_PADDING_FACTOR = 0.2;
const BREATHE_COUNT = 1;

const WIGGLE_DISTANCE = 8;
const WIGGLE_MIN_POSITIONS = 15;
const WIGGLE_MAX_POSITIONS = 20;
const WIGGLE_ABS_MAX_DEGREES = 5;
